### ISSUE TITLE
Support for Android, what's the right approach?

### ISSUE THREAD

**Issue by samitanwer** [wkgcass/msquic-java#2]
I am trying to make this project work for Android. Android, however, supports up to JDK 17 officially. 

When _msquic-java_ is built with 'src compatibility' set to "17", the compiler is unable to find FF&M APIs like _MemorySegment_ . In order to build for Android I converted all import statements (in files under template/src/main/java/io/vproxy/msquic) of _java.lang.foreign.MemorySegment_ to _jdk.incubator.foreign.MemorySegment_ because the _MemorySegment_ API was an incubating API in JDK17. 

However, during the _pniGenerate_ gradle task PNI does a validation for TypeRefs and complaints about "_unable to find typeRef: jdk.incubator.foreign.MemorySegment_" with the following stack trace pointing at _ASTRead_ from the PNI project -

```
class(io/vproxy/msquic/PNICXPLAT_THREAD_CONFIG)#field(Context): unable to find typeRef: jdk.incubator.foreign.MemorySegment
        at io.vproxy.pni.exec.internal.ASTReader.read(ASTReader.java:64)
        at io.vproxy.pni.exec.Generator.generate(Generator.java:36)
        at io.vproxy.pni.exec.Generator$generate.call(Unknown Source)
```
(trace curtailed for brevity)

This seems to be blocking me from continuing to adopt this for Android. Is there a way one can make this work for Android?

**Comment by wkgcass** [comment]
I'm afraid this project doesn't support android. it's built upon Project Panama FFI which doesn't exist in android world. you may replace ffi with jni, but that may require modifying the code generator (panama-native-interface)

there are plenty libraries supporting quic/h3 on android. you don't have to stick to msquic, and msquic doesn't support client side connection migration which is very important for mobile phones

**Comment by samitanwer** [comment]
Thanks for this info @wkgcass. We have some restrictions tying us to MSQuic.

"you may replace ffi with jni" - do you recommend we handwrite the jni and switch to _ByteBuffer_ instead of _MemorySegment_? Or is there any other relatively easier way of making the generator work with JDK17 APIs?

I am no expert with PNI so please excuse if you find my question/s silly.

**Comment by wkgcass** [comment]
i believe writibg a jni wrapper would be easier than modifying the generator, since ffi and jni differs much.

there are a few things to notice:
msquic heavily uses callback functions.
when using panama ffi, we can generate an upcall stub at runtime, which wraps a java method to a function pointer for c to call.
when using jni, you would have to:
    a. for each thread, make a downcall to store JNIEnv on a global threadlocal variable
    b. create an object whose class has a method to handle msquic callback
    c. cache the jmethodID in C
    d. when it is required to register a callback function to msquic, there's also a parameter (usually named 'Context' in msquic) to bind userdata to the callback function, you should retrieve a GlobalRef from your object and pass the ref to 'Context' param
    e. write a callback function in C, which should retrieve a pointer to GlobalRef from 'Context' parameter provided by msquic (which was originally provided when registering the callback function to msquic), then use the stored JNIEnv,jmethodID and the retrieved GlobalRef to make the upcall

the official msquic starts its own worker threads, so you won't have a chance to register JNIEnv to c, but you can use the modified version here (wkgcass/msquic), which allows you to dispatch msquic worker threads by yourself. this is based on the latest release

there's also a jni branch in this repo, which is out-dated and i wasn't familiar with jni nor msquic at that time, but i believe you can grab some code snippets and save some time

**Comment by samitanwer** [comment]
That helps a lot. Thank you! :smiley:
